#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage: checkout-installer/render.sh [--check] <consumer-repository>

Generate the consumer's self-contained top-level install.sh from
scripts/checkout-installer.conf. The config must set
CHECKOUT_INSTALLER_ENABLED=true.

--check renders to a temporary file and fails if the committed installer differs.
EOF
}

die() {
  printf 'checkout-installer-render: %s\n' "$*" >&2
  exit 1
}

check=false
case $#:${1:-} in
  1:*) ;;
  2:--check)
    check=true
    shift
    ;;
  *)
    usage
    exit 2
    ;;
esac

source_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
template="$source_dir/install.sh.in"
consumer=$1
config="$consumer/scripts/checkout-installer.conf"
output="$consumer/install.sh"
generated_header='# Generated by cgraf78/actions checkout-installer. Do not edit.'

[[ -d "$consumer" && ! -L "$consumer" ]] ||
  die "consumer repository must be a regular directory: $consumer"
[[ -f "$config" && ! -L "$config" ]] ||
  die "checkout installer config must be a regular file: $config"
[[ -f "$template" && ! -L "$template" ]] ||
  die "installer template must be a regular file: $template"

# Clear every input before sourcing the consumer policy. A maintainer's shell
# environment must not silently alter generated, committed installer bytes.
CHECKOUT_INSTALLER_ENABLED=
CHECKOUT_INSTALLER_REPO=
CHECKOUT_INSTALLER_REF=
CHECKOUT_INSTALLER_DELEGATE=
CHECKOUT_INSTALLER_DEFAULT_DESTINATION=
CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE=

# shellcheck source=/dev/null
. "$config"

if [[ ${CHECKOUT_INSTALLER_ENABLED:-} != true ]]; then
  if [[ -f "$output" && ! -L "$output" &&
    $(sed -n '2p' "$output") == "$generated_header" ]]; then
    if [[ "$check" == true ]]; then
      die "generated installer remains while checkout installer policy is disabled: $output"
    fi
    rm -f "$output"
    printf 'checkout-installer-render: removed disabled generated installer %s\n' \
      "$output"
    exit 0
  fi
  printf 'checkout-installer-render: checkout installer is not enabled in %s\n' \
    "$config"
  exit 0
fi

[[ ${CHECKOUT_INSTALLER_REPO:-} =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ ]] ||
  die 'CHECKOUT_INSTALLER_REPO must be an owner/repository name'

checkout_owner=${CHECKOUT_INSTALLER_REPO%%/*}
checkout_slug=${CHECKOUT_INSTALLER_REPO##*/}
for name in "$checkout_owner" "$checkout_slug"; do
  [[ "$name" != . && "$name" != .. ]] ||
    die 'CHECKOUT_INSTALLER_REPO must not contain dot segments'
done
: "${CHECKOUT_INSTALLER_REF:=main}"
: "${CHECKOUT_INSTALLER_DELEGATE:=support/install-checkout.sh}"
: "${CHECKOUT_INSTALLER_DEFAULT_DESTINATION:=xdg}"
: "${CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE:=}"

case "$CHECKOUT_INSTALLER_REF" in
  '' | -* | /* | */ | *//* | *..* | *[!A-Za-z0-9._/-]*)
    die 'CHECKOUT_INSTALLER_REF must be a safe branch name'
    ;;
esac
case "$CHECKOUT_INSTALLER_DELEGATE" in
  '' | -* | . | .. | /* | ./* | */./* | */. | *[!A-Za-z0-9._/-]* | *//* | ../* | */../* | */..)
    die 'CHECKOUT_INSTALLER_DELEGATE must be a safe relative path'
    ;;
esac
[[ "$CHECKOUT_INSTALLER_DELEGATE" != install.sh ]] ||
  die 'CHECKOUT_INSTALLER_DELEGATE must not be install.sh'
if [[ -n "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" ]]; then
  case "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" in
    -* | . | .. | /* | ./* | */./* | */. | *[!A-Za-z0-9._/-]* | *//* | ../* | */../* | */..)
      die 'CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE must be a safe relative path'
      ;;
  esac
  [[ "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" != install.sh ]] ||
    die 'CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE must not be install.sh'
  [[ "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" != "$CHECKOUT_INSTALLER_DELEGATE" ]] ||
    die 'CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE must differ from CHECKOUT_INSTALLER_DELEGATE'
fi
case "$CHECKOUT_INSTALLER_DEFAULT_DESTINATION" in
  xdg | shdeps) ;;
  *)
    die 'CHECKOUT_INSTALLER_DEFAULT_DESTINATION must be xdg or shdeps'
    ;;
esac

delegate="$consumer/$CHECKOUT_INSTALLER_DELEGATE"
[[ -f "$delegate" && ! -L "$delegate" ]] ||
  die "checkout installer delegate must be a regular file: $delegate"
if [[ -n "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" ]]; then
  post_install="$consumer/$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE"
  [[ -f "$post_install" && ! -L "$post_install" ]] ||
    die "checkout installer post-install command must be a regular file: $post_install"
fi

if [[ "$check" != true && (-e "$output" || -L "$output") ]]; then
  [[ -f "$output" && ! -L "$output" &&
    $(sed -n '2p' "$output") == "$generated_header" ]] ||
    die "refusing to overwrite consumer-owned installer: $output"
fi

tmp=$(mktemp "$consumer/.install.sh.XXXXXX")
trap 'rm -f "$tmp"' EXIT

post_install_block=false
while IFS= read -r line || [[ -n "$line" ]]; do
  marker_line=${line#"${line%%[![:space:]]*}"}
  case "$marker_line" in
    '# @CHECKOUT_POST_INSTALL_BEGIN@')
      [[ "$post_install_block" == false ]] ||
        die 'installer template contains a nested post-install block'
      post_install_block=true
      continue
      ;;
    '# @CHECKOUT_POST_INSTALL_END@')
      [[ "$post_install_block" == true ]] ||
        die 'installer template closes an unopened post-install block'
      post_install_block=false
      continue
      ;;
  esac
  if [[ "$post_install_block" == true &&
    -z "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" ]]; then
    continue
  fi
  line=${line//@CHECKOUT_REPO@/$CHECKOUT_INSTALLER_REPO}
  line=${line//@CHECKOUT_SLUG@/$checkout_slug}
  line=${line//@CHECKOUT_REF@/$CHECKOUT_INSTALLER_REF}
  line=${line//@CHECKOUT_DELEGATE@/$CHECKOUT_INSTALLER_DELEGATE}
  line=${line//@CHECKOUT_DEFAULT_DESTINATION@/$CHECKOUT_INSTALLER_DEFAULT_DESTINATION}
  line=${line//@CHECKOUT_POST_INSTALL_DELEGATE@/$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE}
  printf '%s\n' "$line" >>"$tmp"
done <"$template"
[[ "$post_install_block" == false ]] ||
  die 'installer template contains an unterminated post-install block'

if grep -Eq '@[A-Z][A-Z0-9_]*@' "$tmp"; then
  die 'installer template contains an unresolved token'
fi

chmod 0755 "$tmp"
if [[ "$check" == true ]]; then
  [[ -f "$output" && ! -L "$output" && -x "$output" ]] ||
    die "generated installer must be a regular executable: $output"
  if git -C "$consumer" rev-parse --show-toplevel >/dev/null 2>&1; then
    git -C "$consumer" ls-files --error-unmatch install.sh >/dev/null 2>&1 ||
      die "generated installer is not tracked: $output"
    git -C "$consumer" ls-files --error-unmatch -- \
      "$CHECKOUT_INSTALLER_DELEGATE" >/dev/null 2>&1 ||
      die "checkout installer delegate is not tracked: $delegate"
    if [[ -n "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" ]]; then
      git -C "$consumer" ls-files --error-unmatch -- \
        "$CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE" >/dev/null 2>&1 ||
        die "checkout installer post-install command is not tracked: $post_install"
    fi
  fi
  # Git is already part of the checkout-installer contract. Its no-index diff
  # keeps drift verification exact without adding a hidden diffutils/cmp
  # dependency on minimal Arch, Fedora, or Alpine environments.
  if ! command git diff --no-index --quiet --no-ext-diff --no-textconv -- \
    "$tmp" "$output"; then
    die "generated installer differs; run checkout-installer/render.sh $consumer"
  fi
  rm -f "$tmp"
  trap - EXIT
  printf 'checkout-installer-render: verified %s\n' "$output"
  exit 0
fi

mv "$tmp" "$output"
trap - EXIT
printf 'checkout-installer-render: %s\n' "$output"
