#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage: release-installer/render.sh [--check] <consumer-repository>

Generate the consumer's self-contained top-level install.sh from
scripts/release.conf. The config must set RELEASE_STANDALONE_INSTALLER=true.

--check renders to a temporary file and fails if the committed installer differs.
EOF
}

die() {
  printf 'release-installer-render: %s\n' "$*" >&2
  exit 1
}

check=false
case $#:${1:-} in
  1:*) ;;
  2:--check)
    check=true
    shift
    ;;
  *)
    usage
    exit 2
    ;;
esac

source_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
template="$source_dir/install.sh.in"
consumer=$1
config="$consumer/scripts/release.conf"
output="$consumer/install.sh"
generated_header='# Generated by cgraf78/actions release-installer. Do not edit.'

[[ -d "$consumer" && ! -L "$consumer" ]] ||
  die "consumer repository must be a regular directory: $consumer"
[[ -f "$config" && ! -L "$config" ]] ||
  die "release config must be a regular file: $config"
[[ -f "$template" && ! -L "$template" ]] ||
  die "installer template must be a regular file: $template"

# Clear every input before sourcing the consumer policy. A maintainer's shell
# environment must not silently alter generated, committed installer bytes.
RELEASE_STANDALONE_INSTALLER=
RELEASE_SLUG=
RELEASE_REPO=
RELEASE_ASSET_NAME=
RELEASE_BINARY=
RELEASE_BINARY_DEST=
RELEASE_PAYLOAD_FILES=()

# shellcheck source=/dev/null
. "$config"

if [[ ${RELEASE_STANDALONE_INSTALLER:-} != true ]]; then
  if [[ -f "$output" && ! -L "$output" &&
    $(sed -n '2p' "$output") == "$generated_header" ]]; then
    if [[ "$check" == true ]]; then
      die "generated installer remains while standalone installer policy is disabled: $output"
    fi
    rm -f "$output"
    printf 'release-installer-render: removed disabled generated installer %s\n' \
      "$output"
    exit 0
  fi
  printf 'release-installer-render: standalone installer is not enabled in %s\n' \
    "$config"
  exit 0
fi

for name in RELEASE_SLUG RELEASE_ASSET_NAME RELEASE_BINARY; do
  value=${!name:-}
  [[ -n "$value" && "$value" != . && "$value" != .. &&
    "$value" != *[!A-Za-z0-9._-]* ]] ||
    die "$name must be a safe non-empty name"
done

: "${RELEASE_REPO:=cgraf78/$RELEASE_SLUG}"
: "${RELEASE_BINARY_DEST:=$RELEASE_BINARY}"
[[ "$RELEASE_REPO" =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ ]] ||
  die "RELEASE_REPO must be an owner/repository name"
case "$RELEASE_BINARY_DEST" in
  '' | . | .. | /* | ./* | */./* | */. | *[!A-Za-z0-9._/-]* | *//* | ../* | */../* | */..)
    die "RELEASE_BINARY_DEST must be a safe relative archive path"
    ;;
esac

manpage_path=
for entry in ${RELEASE_PAYLOAD_FILES[@]+"${RELEASE_PAYLOAD_FILES[@]}"}; do
  if [[ "$entry" == "man/man1/$RELEASE_BINARY.1" ]]; then
    manpage_path=$entry
  fi
done

if [[ "$check" != true && (-e "$output" || -L "$output") ]]; then
  [[ -f "$output" && ! -L "$output" &&
    $(sed -n '2p' "$output") == "$generated_header" ]] ||
    die "refusing to overwrite consumer-owned installer: $output"
fi

tmp=$(mktemp "$consumer/.install.sh.XXXXXX")
trap 'rm -f "$tmp"' EXIT

while IFS= read -r line || [[ -n "$line" ]]; do
  line=${line//@RELEASE_SLUG@/$RELEASE_SLUG}
  line=${line//@RELEASE_REPO@/$RELEASE_REPO}
  line=${line//@RELEASE_ASSET_NAME@/$RELEASE_ASSET_NAME}
  line=${line//@RELEASE_BINARY@/$RELEASE_BINARY}
  line=${line//@RELEASE_BINARY_DEST@/$RELEASE_BINARY_DEST}
  line=${line//@RELEASE_MANPAGE_PATH@/$manpage_path}
  printf '%s\n' "$line" >>"$tmp"
done <"$template"

if grep -Eq '@[A-Z][A-Z0-9_]*@' "$tmp"; then
  die "installer template contains an unresolved token"
fi

chmod 0755 "$tmp"
if [[ "$check" == true ]]; then
  [[ -f "$output" && ! -L "$output" && -x "$output" ]] ||
    die "generated installer must be a regular executable: $output"
  if git -C "$consumer" rev-parse --show-toplevel >/dev/null 2>&1 &&
    ! git -C "$consumer" ls-files --error-unmatch install.sh >/dev/null 2>&1; then
    die "generated installer is not tracked: $output"
  fi
  if ! cmp -s "$tmp" "$output"; then
    die "generated installer differs; run release-installer/render.sh $consumer"
  fi
  rm -f "$tmp"
  trap - EXIT
  printf 'release-installer-render: verified %s\n' "$output"
  exit 0
fi
mv "$tmp" "$output"
trap - EXIT
printf 'release-installer-render: %s\n' "$output"
